# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 284338400e2d2290ec4b3edbb61947edef25d4dc0cda35c47d85f77503dd4c3ac84289711289ab37e8ce688dbb9f366cbcdae4f431ab085b7b813ce0cf063808

test:
  secret_key_base: 7cbe1504addb0462e0ec508f646c9ac53c872f67eafd7dbc2b21ec3ca014e1aee6745b1d5b850c2892386527c4f153bc24f15bbd4a1aaeba4f57d83bc8e5ee1a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
